#pragma kernel Cubes

int cubes_number;
float radius;
float3 sphere_center, position;

RWBuffer<float4> cubes;

int coords_to_index(int3 id)
{
    return id.x * cubes_number * cubes_number + id.y * cubes_number + id.z;
}

[numthreads(3,3,3)]
void Cubes(uint3 id : SV_DispatchThreadID)
{
    float4 cube;
    cube.xyz = id;
    cube.w = -(length(cube.xyz + position - sphere_center) - radius);
    
    cubes[coords_to_index(id)] = cube;
}
